baseurl = "/"
title = "stjean.me"
languageCode = "en-us"

buildDrafts = false
buildFuture = false

relativeURLs = false
canonifyURLs = false

publishdir = "_site"

[blackfriday]
plainIDAnchors = true
