# fly.toml app configuration file generated for palatelier-ca on 2024-12-30T16:39:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stjean-me"
primary_region = "yul" # Montreal region

[build]
dockerfile = "Dockerfile"

[env]
PORT = "80"

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
